using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace UnityDocsIndex.Editor
{
    public static class SkillInstaller
    {
        private const string SkillRelativePath = ".claude/skills/unity-docs";
        private const string PackageName = "com.tsuchigoe.agent-unity-docs";

        public static string ProjectRoot => Path.GetDirectoryName(Application.dataPath);
        public static string SkillPath => Path.Combine(ProjectRoot, SkillRelativePath);
        public static string DocsPath => Path.Combine(SkillPath, "docs");
        public static string IndexPath => Path.Combine(SkillPath, "references", "index.txt");
        public static string DocsRelativeRoot => SkillRelativePath + "/docs";

        public static bool IsSkillInstalled()
        {
            return File.Exists(Path.Combine(SkillPath, "SKILL.md"));
        }

        public static bool DocsExist()
        {
            return Directory.Exists(Path.Combine(DocsPath, "Manual"))
                || Directory.Exists(Path.Combine(DocsPath, "ScriptReference"));
        }

        public static bool IndexExists()
        {
            return File.Exists(IndexPath);
        }

        /// <summary>
        /// Install the skill by copying template files from the UPM package to the project.
        /// Skips docs/ and references/ (those are generated by setup).
        /// </summary>
        public static SkillInstallResult InstallSkill()
        {
            if (IsSkillInstalled())
                return SkillInstallResult.AlreadyInstalled;

            var packageSkillPath = GetPackageSkillPath();
            if (string.IsNullOrEmpty(packageSkillPath))
                return SkillInstallResult.ErrorPackageNotFound;

            try
            {
                CopySkillTemplate(packageSkillPath, SkillPath);

#if UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX
                MakeExecutable(Path.Combine(SkillPath, "scripts", "setup.sh"));
#endif

                Debug.Log($"Skill installed at {SkillPath}");
                return SkillInstallResult.Success;
            }
            catch (Exception e)
            {
                Debug.LogError($"Failed to install skill: {e.Message}");
                return SkillInstallResult.ErrorWriteFailed;
            }
        }

        /// <summary>
        /// Update .gitignore to allow .claude/skills/ while keeping other .claude/ content ignored.
        /// </summary>
        public static GitignoreResult EnsureGitignoreAllowsSkill()
        {
            var gitignorePath = Path.Combine(ProjectRoot, ".gitignore");

            if (!File.Exists(gitignorePath))
                return GitignoreResult.AlreadyPresent;

            try
            {
                var content = File.ReadAllText(gitignorePath);

                // Already configured
                if (content.Contains("!.claude/skills/"))
                    return GitignoreResult.AlreadyPresent;

                // .claude/ fully ignored → change to .claude/* with negation
                if (content.Contains(".claude/"))
                {
                    content = content.Replace(".claude/", ".claude/*\n!.claude/skills/");
                    File.WriteAllText(gitignorePath, content);
                    Debug.Log("Updated .gitignore to allow .claude/skills/");
                    return GitignoreResult.SuccessUpdated;
                }

                return GitignoreResult.AlreadyPresent;
            }
            catch (Exception e)
            {
                Debug.LogError($"Failed to update .gitignore: {e.Message}");
                return GitignoreResult.ErrorWriteFailed;
            }
        }

        /// <summary>
        /// Remove legacy index markers from CLAUDE.md if present.
        /// </summary>
        public static void CleanLegacyIndex()
        {
            var claudeMdPath = Path.Combine(ProjectRoot, "CLAUDE.md");
            if (!File.Exists(claudeMdPath))
                return;

            var content = File.ReadAllText(claudeMdPath);
            var startMarker = DocsIndexGenerator.StartMarker;
            var endMarker = DocsIndexGenerator.EndMarker;

            var startIdx = content.IndexOf(startMarker, StringComparison.Ordinal);
            var endIdx = content.IndexOf(endMarker, StringComparison.Ordinal);

            if (startIdx == -1 || endIdx == -1 || endIdx <= startIdx)
                return;

            var before = content.Substring(0, startIdx).TrimEnd('\n', '\r');
            var after = content.Substring(endIdx + endMarker.Length).TrimStart('\n', '\r');

            content = string.IsNullOrEmpty(before)
                ? after
                : string.IsNullOrEmpty(after)
                    ? before + "\n"
                    : before + "\n" + after;

            File.WriteAllText(claudeMdPath, content);
            Debug.Log("Removed legacy index from CLAUDE.md");
        }

        /// <summary>
        /// Migrate legacy .unity-docs/ to skill directory.
        /// </summary>
        public static bool MigrateLegacyDocs()
        {
            var legacyPath = Path.Combine(ProjectRoot, ".unity-docs");
            if (!Directory.Exists(Path.Combine(legacyPath, "Manual")))
                return false;

            try
            {
                Directory.CreateDirectory(DocsPath);

                foreach (var dir in Directory.GetDirectories(legacyPath))
                {
                    var dirName = Path.GetFileName(dir);
                    var destDir = Path.Combine(DocsPath, dirName);
                    if (Directory.Exists(destDir))
                        Directory.Delete(destDir, true);
                    Directory.Move(dir, destDir);
                }

                foreach (var file in Directory.GetFiles(legacyPath))
                {
                    var destFile = Path.Combine(DocsPath, Path.GetFileName(file));
                    File.Move(file, destFile);
                }

                Directory.Delete(legacyPath, false);
                Debug.Log($"Migrated .unity-docs/ → {DocsPath}");
                return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"Failed to migrate legacy docs: {e.Message}");
                return false;
            }
        }

        private static string GetPackageSkillPath()
        {
            var packagePath = Path.GetFullPath($"Packages/{PackageName}");
            if (!Directory.Exists(packagePath))
                return null;

            var skillPath = Path.Combine(packagePath, SkillRelativePath);
            return Directory.Exists(skillPath) ? skillPath : null;
        }

        private static void CopySkillTemplate(string sourceDir, string destDir)
        {
            Directory.CreateDirectory(destDir);

            foreach (var file in Directory.GetFiles(sourceDir))
            {
                var fileName = Path.GetFileName(file);
                File.Copy(file, Path.Combine(destDir, fileName), true);
            }

            foreach (var dir in Directory.GetDirectories(sourceDir))
            {
                var dirName = Path.GetFileName(dir);
                // Skip generated directories
                if (dirName == "docs" || dirName == "references")
                    continue;
                CopySkillTemplate(dir, Path.Combine(destDir, dirName));
            }
        }

#if UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX
        private static void MakeExecutable(string path)
        {
            if (!File.Exists(path))
                return;

            try
            {
                var process = new System.Diagnostics.Process();
                process.StartInfo.FileName = "chmod";
                process.StartInfo.Arguments = $"+x \"{path}\"";
                process.StartInfo.UseShellExecute = false;
                process.StartInfo.CreateNoWindow = true;
                process.Start();
                process.WaitForExit();
            }
            catch (Exception e)
            {
                Debug.LogWarning($"Failed to set executable permission: {e.Message}");
            }
        }
#endif
    }
}
